""" The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
We can see that 28 is the first triangle number to have over five divisors. What is the value of the first triangle number to have over five hundred divisors? """

# Expected answer - 76576500

import math 

import time 
start = time.time()

def divisors(n):
    divisors = 0
    for i in range(1, round(math.sqrt(n))+1):
        if n % i == 0:
            divisors += 2
    return divisors

def minimumNumberOfDivisors(n):
    i = 1
    while True:
        tN = int(i * (i+1) / 2)
        if divisors(tN) > n:
            return tN
            break
        i += 1

print(minimumNumberOfDivisors(500))

end = time.time()
print(f"Duration is {round(end-start)} sec")