"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the 
even-valued terms"""

def fibTotal():
    prev, curr = 1,2
    list = [prev,curr]
    evenList =[2]
    oddList =[1]
    total = 0
    while True:
        prev, curr = curr, prev + curr
        if curr >= 1_000:
            break
        elif curr % 2 == 0:
            total += curr
            evenList.append(curr)
            list.append(curr)
        else:
            oddList.append(curr)
            list.append(curr)
    return total

print(fibTotal())